name: Build Package

on:
  push:
    tags:        
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: dotnet test --configuration Release
    - name: Build
      run: dotnet pack --configuration Release zsyncnet/
    - uses: actions/upload-artifact@v2
      with:
        name: nuget-package
        path: ./**.nupkg
    #- name: Publish
    #  run: dotnet nuget push **.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/beowulfstratops/index.json
